version: "2"

services:
    postgres:
        image: postgres:13
        volumes:
            - postgres_volume:/var/lib/postgresql/data
            - ./dockerConfig/postgres-dev-init.sql:/docker-entrypoint-initdb.d/init.sql
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - 5433:5432

    myapp:
        build: .
        ports:
            - "8000:8000"
        environment:
            - DB_CONNECTION=pgsql
            - DB_HOST=postgres
            - DB_PORT=5432
            - DB_USERNAME=laravel
            - DB_PASSWORD=laravel
            - DB_DATABASE=laravel_app
        volumes:
            - "./:/var/www/html"
        depends_on:
            - postgres

volumes:
    postgres_volume:
